##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False  # 添加此参数
    usd_path: "robot/piper_description/piper.usda" 
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    # usd_flip_joints: {
    #    "joint1",  # 尝试翻转第一个关节方向
    #    "joint2",
    #    "joint3",
    #    "joint4": "Z",
    #    "joint5": "Z",
    #   "joint6"
    # }
    # usd_flip_joints: {
    #    "joint1": "Z",  # 尝试翻转第一个关节方向
    #    "joint2": "Z",
    #    "joint3": "Z",
    #    "joint4": "Z",
    #    "joint5": "Z",
    #   "joint6": "Z"
    # }
    usd_flip_joint_limits: []

    urdf_path: "robot/piper_description/piper_description.urdf"
    asset_root_path: "robot/piper_description"
    
    base_link: "base_link"
    ee_link: "link6"
    #link_names: null
    lock_joints: {"joint7": 0.0}
    extra_links: null

    
    collision_link_names: ['link1','link2', 'link3', 'link4', 
    'link5' ,'link6', 'link7'] # List[str]
    collision_spheres:
      link1:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.025
      link2:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.025
        - "center": [0.287, -0.013, -0.0]
          "radius": 0.025
        - "center": [0.048, -0.002, -0.0]
          "radius": 0.025
        - "center": [0.096, -0.004, -0.0]
          "radius": 0.025
        - "center": [0.144, -0.007, -0.0]
          "radius": 0.025
        - "center": [0.192, -0.009, -0.0]
          "radius": 0.025
        - "center": [0.24, -0.011, -0.0]
          "radius": 0.025

      link3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.025
        - "center": [-0.017, -0.182, 0.0]
          "radius": 0.02
        - "center": [-0.004, -0.047, 0.0]
          "radius": 0.0237
        - "center": [-0.009, -0.094, 0.0]
          "radius": 0.0224
        - "center": [-0.013, -0.138, 0.0]
          "radius": 0.0212
      link4:
         - "center": [0.0, 0.0, 0.0]
           "radius": 0.02
      link5: 
        - "center": [0.006, -0.058, 0.0]
          "radius": 0.025
      link6: 
        - "center": [0.003, 0.0, 0.026]
          "radius": 0.025
      link7:
        - "center": [0.001, 0.001, 0.001]
          "radius": 0.025 #0.05


    collision_sphere_buffer: 0.002
    extra_collision_spheres: {}
    self_collision_ignore: {
      "link1": ["base_link","link2"],
      "link2": ["link1", "link3"],
      "link3": ["link2", "link4"],
      "link4": ["link3","link5"],
      "link5": ["link4", "link6"],
      "link6": ["link7","link5"],

      
      }
    self_collision_buffer: {
      'link1': 0.02,
      'link2': 0.02, 
      'link3': 0.02, 
      'link4': 0.02,
      'link5' : 0.02,
      'link6' : 0.02,
      'link7': 0.02,
      } 
      
    use_global_cumul: True
    mesh_link_names: ['link1','link2', 'link3', 'link4', 
    'link5' ,'link6']  # List[str]

    cspace:
      joint_names: ['joint1','joint2', 'joint3','joint4' ,'joint5', 'joint6'
      ]
      retract_config:  [0.0, 0.2, -0.2, 0.0, 0.1, 0.0]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1
      
      
      
